# Generated by Django 2.0.4 on 2018-10-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('data_nasc', models.DateField()),
                ('email', models.CharField(max_length=160)),
                ('cidade', models.CharField(max_length=160)),
                ('nacionalidade', models.CharField(max_length=160)),
                ('sexy', models.CharField(choices=[('0', 'Masculino'), ('1', 'Feminino')], max_length=1)),
                ('nacao', models.CharField(choices=[('0', 'Brasileiro'), ('1', 'USA'), ('2', 'Japão'), ('3', 'Coreano')], max_length=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-date', '-priority', 'event')},
        ),
    ]
